apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups:
  - kubernetes.dev
  resources:
  - weatherdatas
  verbs:
  - '*'
- apiGroups:
  - kubernetes.dev
  resources:
  - weatherlocations
  verbs:
  - get
  - list
- apiGroups:
  - kubernetes.dev
  resources:
  - weatherlocations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ''
  - admissionregistration.k8s.io
  resources:
  - services
  - validatingwebhookconfigurations
  verbs:
  - create
  - get
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
